name: Server Continuous Integration

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Docker Image ğŸ—ï¸
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out repository code ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          repository: pollak-projects/csengo-ts
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx ğŸš€
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry ğŸš¢
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ğŸ—ï¸
        uses: docker/build-push-action@v3
        with:
          context: ./csengo-ts-server-v2
          platforms: linux/amd64
          file: ./csengo-ts-server-v2/Dockerfile
          push: true
          tags: ghcr.io/pollak-projects/csengo-ts/server-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
